#!/bin/sh
set -e

MAGENTO_ENV=${DOCUMENT_ROOT}/app/etc/env.php
MAGENTO_ENV_TEMPLATE=${DOCUMENT_ROOT}/app/etc/env.php.template

while [ ! -f "${MAGENTO_ENV}" ]
do
		echo "Waiting for ${MAGENTO_ENV}..."
		if [ -f "${MAGENTO_ENV_TEMPLATE}" ]; then
				if [ ! -f "${MAGENTO_ENV}" ]; then
        		echo "cp ${MAGENTO_ENV_TEMPLATE} ${MAGENTO_ENV}"
            cp "${MAGENTO_ENV_TEMPLATE}" "${MAGENTO_ENV}"
        fi
    fi
    sleep 2;
done

echo "${DOCUMENT_ROOT}/bin/magento cache:flush"
"${DOCUMENT_ROOT}"/bin/magento cache:flush