#!/bin/sh

MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-"root"}
MYSQL_PASSWORD=${MAGENTO_DATABASE_PWD:-"magento2"}
MYSQL_DATABASE=${MAGENTO_DATABASE_DB:-"magento2"}
MYSQL_USER=${MAGENTO_DATABASE_USER:-"magento2"}

echo "[i] Creating initial DBs"

echo 'Initializing database'
mysql_install_db --user=root --datadir=/var/lib/mysql
echo 'Database initialized'

if [ ! -d "/run/mysqld" ]; then
    mkdir -p /run/mysqld
fi

tfile=`mktemp`
if [ ! -f "${tfile}" ]; then
    return 1
fi

cat << EOF > ${tfile}
USE mysql;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY "${MYSQL_ROOT_PASSWORD}" WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;
EOF

if [ "${MYSQL_DATABASE}" != "" ]; then
    echo "[i] Creating database: ${MYSQL_DATABASE}"
    echo "CREATE DATABASE IF NOT EXISTS \`${MYSQL_DATABASE}\` CHARACTER SET utf8 COLLATE utf8_general_ci;" >> ${tfile}

    if [ "${MYSQL_USER}" != "" ]; then
        echo "[i] Creating user: ${MYSQL_USER} with password ${MYSQL_PASSWORD}"
        echo "GRANT ALL ON \`${MYSQL_DATABASE}\`.* to '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';" >> ${tfile}
    fi
fi

/usr/bin/mysqld --user=root --bootstrap --verbose=0 < ${tfile}
rm -f ${tfile}

echo "[i] Sleeping 5 sec"
sleep 5

echo "Starting all process"

exec /usr/bin/mysqld --user=root --console --skip-name-resolve --skip-networking=0 $@ &

sleep 5
echo "[i] Sleeping 5 sec"

