#!/bin/sh
set -e

. /rootfs/magento:entrypoint:template
. /rootfs/magento:entrypoint:env

# Clear Old Config and Env
echo "${DOCUMENT_ROOT}/bin/magento cache:flush"
"${DOCUMENT_ROOT}"/bin/magento cache:flush