#!/bin/sh
set -e

. /rootfs/magento-setup-default
. /rootfs/magento-setup-production
. /rootfs/magento-crontab-installer

VENDOR=${DOCUMENT_ROOT}/vendor

if [ -d "${VENDOR}" ] && [ "$(ls "${VENDOR}")" ]; then
		. /rootfs/magento-system-installer
		. /rootfs/magento-system-setup
else
		echo "${DOCUMENT_ROOT}/vendor is empty."
fi